## Datan analysointi K2020_2 - Tehtävät kerta 1 - ratkaisut

Palauta Optiman palautuslaatikkoon viimeistään su 19.1.  Kirjoita palautuslaatikon kommenttikenttään, mitä tehtävät olet tehnyt kokonaan/osittain.

**Tee tehtävät ilman for-silmukoita tms.**

**Opiskelijan nimi**:

## 1. NumPy-taulukot  - baseball

Alla on lista height, jossa on baseball-pelaajien pituuksia tuumina (1 tuuma = 2,54 cm), ja lista weight, jossa on vastaavassa järjestyksessä pelaajien painot nauloina (1 naula = 0,453592 kg).

Tee näistä NumPy-taulukot, ja laske niiden avulla NumPy-taulukko, jossa on pelaajien painoindeksit. Painoindeksi lasketaan kaavalla

paino (kg)/pituus (m) ^2  
(eli paino jaettuna pituuden neliöllä, joudut muuttamaan tuumat ja naulat yksiköiksi m ja kg).

Suodata/lajittele taulukkoa löytääksesi vastauksen kysymyksiin:

* Kuinka monta pelaajaa on kaikkiaan?
* Kuinka monella painoindeksi on alle 20 ?
* Mikä on suurin painoindeksi niistä pelaajista, joiden pituus on yli 200 cm?
* Mikä on painoindeksien keskiarvo ja mediaani?

In [8]:
import numpy as np

height = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]

weight = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]

painot = np.array(weight)*0.453592
pituudet = np.array(height)*0.0254
bmit = painot/pituudet**2

print('pelaajia: ',len(painot))
print('bmi alle 20: ',len(bmit[bmit<20]))
print('suurin painoindeksi niistä pelaajista, joiden pituus on yli 200 cm: ', bmit[pituudet>2].max())
print('painoindeksien keskiarvo: ', np.mean(bmit))
print('painoindeksien mediaani: ', np.median(bmit))

pelaajia:  1015
bmi alle 20:  1
suurin painoindeksi niistä pelaajista, joiden pituus on yli 200 cm:  32.66944588688089
painoindeksien keskiarvo:  26.05684565448554
painoindeksien mediaani:  26.048609299434666

## 2. Nopanheitto
Heitettäessä kolmea noppaa todennäköisyys että kaikkien silmäluvut on erit on n. 56 %.

Testaa tätä "heittämällä" kolmea noppaa 10 miljoonaa kertaa:
* Tee  NumPy:n randint-funktiolla NumPy-taulukko, jossa on 10 000 000 kpl satunnaislukuja väliltä 1-6. https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html#numpy.random.randint
* Tee samanlainen taulukko vielä 2 kertaa
* Tee sitten NumPy-taulukko jossa on True (tai 1) kun kolmessa "noppataulukossa" on kyseisellä paikalla kaikissa eri luku, ja False (tai 0), jos ei ole 
* Laske montako True-alkioita taulukossa on ja jaa se alkioiden määrällä (pitäisi tulla noin 0,556)

Voit tehdä "noppataulukoista" DataFramen tai tutkia pelkästään NynPy-taulukkoja

In [16]:
import numpy as np

noppa1 = np.random.randint(1,7,10000000)
noppa2 = np.random.randint(1,7,10000000)
noppa3 = np.random.randint(1,7,10000000)


onko_erit = (noppa1 != noppa2) & (noppa2 != noppa3) & (noppa1 != noppa3)

print("Erien osuus: ", onko_erit.sum()/len(onko_erit))

Erien osuus:  0.5556766

## 3. DataFrame - Veikkausliiga

Alla on sisäkkäisisitä sanakirjoista koostuva tietorakenne, jossa on jalkapallon Veikkausliigajoukkueiden sarjasijoitukset 1990-2019.

Tee sanakirjasta DataFrame, jossa vuodet ovat riviotsikoita ja joukkueet sarakeotsikoita. 

Suodata ja tulosta sitten DataFramesta seuraavat näkymät tai uudet DataFramet/Seriekset (älä valitse rivejä "käsin"):
* Ne rivit jolloin JJK:n sijoitus on ollut kymmenen parhaan joukossa. Vain JJK:n sarake
* Ne rivit jolloin RoPS:n sijoitus on ollut pienempi kuin HJK:n sijoitus. Vain RoPS:n ja HJK:n sarakkeet.
* Ne rivit jolloin Ilveksen sijoitus ei ole ollut NaN ja HJK:n sijoitus on ollut 3 parhaan joukossa. Vain Ilveksen ja HJK:n sarakkeet
* Rivit vuosilta 1995-2005. Vain HJK:n sarake.


Muokkaa sitten DataFramea niin, että kaikki yli 10 olevat sijoitukset korvataan merkkijonolla 'yli 10'.

In [29]:
veikkausliiga = {1990: {'HJK': 1,'Kuusysi': 2,'MP': 3,'Reipas': 4,'RoPS': 5,'KuPS': 6,'TPS': 7,'Haka': 8,'Ilves': 9,'OTP': 10,'KPV': 11,'Kumu': 12},
1991: {'Kuusysi': 1,'MP': 2,'Haka': 3,'Jaro': 4,'HJK': 5,'Ilves': 6,'RoPS': 7,'Jazz': 8,'TPS': 9,'KuPS': 10,'OTP': 11,'Reipas': 12},
1992: {'HJK': 1,'Kuusysi': 2,'Jazz': 3,'MYPA': 4,'Jaro': 5,'Haka': 6,'RoPS': 7,'Ilves': 8,'TPS': 9,'MP': 10,'FC/AC Oulu': 11,'KuPS': 12},
1993: {'Jazz': 1,'MYPA': 2,'HJK': 3,'Kuusysi': 4,'FinnPa': 5,'TPV': 6,'RoPS': 7,'TPS': 8,'MP': 9,'Haka': 10,'Jaro': 11,'Ilves': 12},
1994: {'TPV': 1,'MYPA': 2,'HJK': 3,'Jazz': 4,'RoPS': 5,'Haka': 6,'Jaro': 7,'TPS': 8,'Kuusysi': 9,'FinnPa': 10,'MP': 11,'Ilves': 12,'FC/AC Oulu': 13,'KuPS': 14},
1995: {'Haka': 1,'MYPA': 2,'HJK': 3,'Jazz': 4,'Jaro': 5,'TPS': 6,'Ilves': 7,'FinnPa': 8,'RoPS': 9,'VPS': 10,'MP': 11,'TPV': 12,'Kuusysi': 13,'Ponnistus': 14},
1996: {'Jazz': 1,'MYPA': 2,'TPS': 3,'FinnPa': 4,'Jaro': 5,'Inter': 6,'VPS': 7,'RoPS': 8,'HJK': 9,'Ilves': 10,'Haka': 11,'MP': 12},
1997: {'HJK': 1,'VPS': 2,'FinnPa': 3,'TPS': 4,'MYPA': 5,'RoPS': 6,'Jazz': 7,'Jaro': 8,'TP-Seinäjoki': 9,'Inter': 10},
1998: {'Haka': 1,'VPS': 2,'PK-35': 3,'HJK': 4,'Jazz': 5,'TPS': 6,'MYPA': 7,'RoPS': 8,'FinnPa': 9,'Jaro': 10},
1999: {'Haka': 1,'HJK': 2,'MYPA': 3,'Jokerit': 4,'Inter': 5,'Jazz': 6,'KooTeePee': 7,'RoPS': 8,'TPS': 9,'Lahti': 10,'VPS': 11,'TPV': 12},
2000: {'Haka': 1,'Jokerit': 2,'MYPA': 3,'HJK': 4,'Jazz': 5,'TamU': 6,'Inter': 7,'Lahti': 8,'RoPS': 9,'VPS': 10,'TPS': 11,'KooTeePee': 12},
2001: {'TamU': 1,'HJK': 2,'MYPA': 3,'Haka': 4,'Inter': 5,'VPS': 6,'Atlantis': 7,'KuPS': 8,'Lahti': 9,'Jazz': 10,'Jokerit': 11,'RoPS': 12},
2002: {'HJK': 1,'MYPA': 2,'Haka': 3,'Allianssi': 4,'TamU': 5,'Inter': 6,'Jaro': 7,'Lahti': 8,'KuPS': 9,'Hämeenlinna': 10,'VPS': 11,'Jazz': 12},
2003: {'HJK': 1,'Haka': 2,'TamU': 3,'MYPA': 4,'Lahti': 5,'Allianssi': 6,'Inter': 7,'Jaro': 8,'TPS': 9,'Jokerit': 10,'Hämeenlinna': 11,'Jazz': 12,'KooTeePee': 13,'KuPS': 14},
2004: {'Haka': 1,'Allianssi': 2,'TamU': 3,'Inter': 4,'TPS': 5,'HJK': 6,'Lahti': 7,'MYPA': 8,'KooTeePee': 9,'TP-47': 10,'Jaro': 11,'RoPS': 12,'Jazz': 13,'Hämeenlinna': 14},
2005: {'MYPA': 1,'HJK': 2,'TamU': 3,'Haka': 4,'Inter': 5,'Lahti': 6,'Allianssi': 7,'KooTeePee': 8,'TPS': 9,'KuPS': 10,'Jaro': 11,'IFK Mariehamn': 12,'RoPS': 13,'TP-47': 14},
2006: {'TamU': 1,'HJK': 2,'Haka': 3,'Honka': 4,'IFK Mariehamn': 5,'MYPA': 6,'TPS': 7,'Lahti': 8,'VPS': 9,'Inter': 10,'KooTeePee': 11,'Jaro': 12,'KuPS': 13},
2007: {'TamU': 1,'Haka': 2,'TPS': 3,'Honka': 4,'MYPA': 5,'IFK Mariehamn': 6,'HJK': 7,'Lahti': 8,'Inter': 9,'VPS': 10,'Jaro': 11,'KooTeePee': 12,'Viikingit': 13,'FC/AC Oulu': 14},
2008: {'Inter': 1,'Honka': 2,'Lahti': 3,'HJK': 4,'MYPA': 5,'TPS': 6,'TamU': 7,'Haka': 8,'Jaro': 9,'RoPS': 10,'VPS': 11,'IFK Mariehamn': 12,'KuPS': 13,'KooTeePee': 14},
2009: {'HJK': 1,'Honka': 2,'TPS': 3,'IFK Mariehamn': 4,'Inter': 5,'Haka': 6,'TamU': 7,'VPS': 8,'MYPA': 9,'Jaro': 10,'Lahti': 11,'KuPS': 12,'JJK': 13,'RoPS': 14},
2010: {'HJK': 1,'KuPS': 2,'TPS': 3,'Honka': 4,'Jaro': 5,'Inter': 6,'TamU': 7,'Haka': 8,'MYPA': 9,'VPS': 10,'FC/AC Oulu': 11,'IFK Mariehamn': 12,'JJK': 13,'Lahti': 14},
2011: {'HJK': 1,'Inter': 2,'JJK': 3,'Honka': 4,'TPS': 5,'KuPS': 6,'IFK Mariehamn': 7,'MYPA': 8,'VPS': 9,'Haka': 10,'Jaro': 11,'RoPS': 12},
2012: {'HJK': 1,'Inter': 2,'TPS': 3,'IFK Mariehamn': 4,'Lahti': 5,'MYPA': 6,'Honka': 7,'VPS': 8,'JJK': 9,'KuPS': 10,'Jaro': 11,'Haka': 12},
2013: {'HJK': 1,'Honka': 2,'VPS': 3,'IFK Mariehamn': 4,'Lahti': 5,'MYPA': 6,'KuPS': 7,'TPS': 8,'Inter': 9,'Jaro': 10,'RoPS': 11,'JJK': 12},
2014: {'HJK': 1,'SJK': 2,'Lahti': 3,'VPS': 4,'IFK Mariehamn': 5,'Jaro': 6,'KuPS': 7,'MYPA': 8,'Inter': 9,'RoPS': 10,'Honka': 11,'TPS': 12},
2015: {'SJK': 1,'RoPS': 2,'HJK': 3,'Inter': 4,'Lahti': 5,'IFK Mariehamn': 6,'HIFK': 7,'Ilves': 8,'KuPS': 9,'VPS': 10,'KooTeePee': 11,'Jaro': 12},
2016: {'IFK Mariehamn': 1,'HJK': 2,'SJK': 3,'VPS': 4,'Ilves': 5,'RoPS': 6,'KuPS': 7,'Lahti': 8,'PS Kemi': 9,'HIFK': 10,'Inter': 11,'PK-35': 12},
2017: {'HJK': 1,'KuPS': 2,'Ilves': 3,'Lahti': 4,'IFK Mariehamn': 5,'SJK': 6,'RoPS': 7,'VPS': 8,'Inter': 9,'PS Kemi': 10,'HIFK': 11,'JJK': 12},
2018: {'HJK': 1,'RoPS': 2,'KuPS': 3,'Honka': 4,'Ilves': 5,'VPS': 6,'Inter': 7,'Lahti': 8,'SJK': 9,'IFK Mariehamn': 10,'TPS': 11,'PS Kemi': 12},
2019: {'KuPS': 1,'Inter': 2,'Honka': 3,'Ilves': 4,'HJK': 5,'IFK Mariehamn': 6,'HIFK': 7,'Lahti': 8,'SJK': 9,'RoPS': 10,'KPV': 11,'VPS': 12}}



import pandas as pd

df = pd.DataFrame(veikkausliiga).T


# .astype(int) muuttaa kokonaisluvuiksi, NaN-arvojen vuoksi tulee liukulukuina

print('\n----- JJK 10 joukossa------------\n')
print(df.loc[df['JJK']<=10, 'JJK'].astype(int))

print('\n----- RoPS HJK:n edellä------------\n')
print(df.loc[df['RoPS']<df['HJK'], ['RoPS','HJK']].astype(int))

print('\n----- Ilves mukana, HJK mitaleilla------------\n')
print(df.loc[df['Ilves'].notnull() & (df['HJK']<4),['Ilves','HJK']].astype(int))

print('\n----- HJK:n vuodet 1995-2005 ------------\n')
print(df.loc[1995:2005,'HJK'].astype(int))

print('\n----- kaikki yli 10 olevat sijoitukset korvataan merkkijonolla \'yli 10\'----------\n')

df[df > 10] = 'yli 10'
print(df.head())

----- JJK 10 joukossa------------

2011    3
2012    9
Name: JJK, dtype: int32

----- RoPS HJK:n edellä------------

      RoPS  HJK
1996     8    9
2015     2    3

----- Ilves mukana, HJK mitaleilla------------

      Ilves  HJK
1990      9    1
1992      8    1
1993     12    3
1994     12    3
1995      7    3
2015      8    3
2016      5    2
2017      3    1
2018      5    1

----- HJK:n vuodet 1995-2005 ------------

1995    3
1996    9
1997    1
1998    4
1999    2
2000    4
2001    2
2002    1
2003    1
2004    6
2005    2
Name: HJK, dtype: int32

----- kaikki yli 10 olevat sijoitukset korvataan merkkijonolla 'yli 10'----------

      HJK Kuusysi      MP  Reipas RoPS    KuPS TPS Haka   Ilves     OTP  ...  \
1990  1.0       2       3       4    5       6   7    8       9      10  ...
1991  5.0       1       2  yli 10    7      10   9    3       6  yli 10  ...
1992  1.0       2      10     NaN    7  yli 10   9    6       8     NaN  ...
1993  3.0       4       9     NaN    7     NaN   8   10  yli 10     NaN  ...
1994  3.0       9  yli 10     NaN    5  yli 10   8    6  yli 10     NaN  ...

     Allianssi Hämeenlinna TP-47 IFK Mariehamn  Honka Viikingit  JJK SJK HIFK  \
1990       NaN         NaN   NaN           NaN    NaN       NaN  NaN NaN  NaN
1991       NaN         NaN   NaN           NaN    NaN       NaN  NaN NaN  NaN
1992       NaN         NaN   NaN           NaN    NaN       NaN  NaN NaN  NaN
1993       NaN         NaN   NaN           NaN    NaN       NaN  NaN NaN  NaN
1994       NaN         NaN   NaN           NaN    NaN       NaN  NaN NaN  NaN

     PS Kemi
1990     NaN
1991     NaN
1992     NaN
1993     NaN
1994     NaN

[5 rows x 38 columns]

## 4. Äärisää
Alla luetaan DataFrameen csv-tiedosto, jossa on päivittäisä säähavaintoja Jyväskylän lentoasemalta vuosilta 1959-2020. (datan lukemisesta enemmän seuraavalla kerralla).

Tutki dataa tulostamalla   
`df.head()`  (5 ekaa riviä)  
`df.tail()`  (5 viimeistä riviä)

Lajittele/suodata sitten DataFramea ja tulosta
* 10 riviä, joissa ylin lämpötila on suurin lajiteltuna ylimmän lämpötilan mukaan. Lajittele niin että päivät, joissa on sama ylin lämpötila, lajitellaan alimman lämpötilan mukaan.
* kaikki tammikuun 1.-15. päivät, jolloin ylin lämpötila on ollut korkeampi kuin ylin lämpötila 2.1.2020 lajiteltuna ylimmän lämpötilan mukaan laskevasti
* tee uusi sarake, jossa on vuorokauden ylimmän ja alimman lämpötilan ero, ja tulosta 10 riviä, joissa on pienin ero

In [1]:
import pandas as pd
df = pd.read_csv('http://student.labranet.jamk.fi/~varpe/datananal2k2020/kerta1/saa_jkl20200105.csv', delimiter = ',')

print('\n----- head-----------\n')
print(df.head())
print('\n----- tail------------\n')
print(df.tail())

#tulostetaan selkeyden vuoksi vain nämä sarakkeet
sarakkeet = ['Vuosi','Kk','Pv','Ylin lämpötila (degC)', 'Alin lämpötila (degC)']

print('\n----- top10 ylimmät------------\n')

print(df[sarakkeet].sort_values(['Ylin lämpötila (degC)','Alin lämpötila (degC)'], ascending = False).head(10))

print('\n----- yli 2.1.2020 -lämpötilat ------------\n')

raja = df[(df['Vuosi'] == 2020) & (df['Kk'] == 1) & (df['Pv'] == 2)]['Ylin lämpötila (degC)']

# raja ei ole nyt luku vaan Series, arvon siitä saa esim float(raja) tai raja.values[0]
raja = raja.values[0]

print(df[sarakkeet][(df['Kk']==1) & (df['Pv']<16) & (df['Ylin lämpötila (degC)']>raja)].sort_values('Ylin lämpötila (degC)',ascending = False))

print('\n----- vrk:n lämpötilaero ------------\n')

df['erotus'] = df['Ylin lämpötila (degC)'] - df['Alin lämpötila (degC)']

#tulostetaan selkeyden vuoksi vain nämä sarakkeet
sarakkeet.append('erotus')

print(df[sarakkeet].sort_values('erotus').head(10))

----- head-----------

   Vuosi  Kk  Pv    Klo Aikavyöhyke  Sademäärä (mm)  Lumensyvyys (cm)  \
0   1959   1   1  00:00         UTC             1.0              34.0
1   1959   1   2  00:00         UTC             1.5              35.0
2   1959   1   3  00:00         UTC            10.6              36.0
3   1959   1   4  00:00         UTC             1.7              38.0
4   1959   1   5  00:00         UTC             7.1              40.0

   Ilman lämpötila (degC)  Ylin lämpötila (degC)  Alin lämpötila (degC)
0                    -4.8                   -3.6                   -9.8
1                    -6.3                   -4.0                   -8.0
2                    -5.2                    0.0                   -8.7
3                    -0.4                    0.7                   -1.1
4                    -1.6                   -0.7                   -2.8

----- tail------------

       Vuosi  Kk  Pv    Klo Aikavyöhyke  Sademäärä (mm)  Lumensyvyys (cm)  \
22280   2020   1   1  00:00         UTC             0.7              20.0
22281   2020   1   2  00:00         UTC            -1.0              20.0
22282   2020   1   3  00:00         UTC             1.9              18.0
22283   2020   1   4  00:00         UTC             0.3              14.0
22284   2020   1   5  00:00         UTC             2.0              15.0

       Ilman lämpötila (degC)  Ylin lämpötila (degC)  Alin lämpötila (degC)
22280                     0.2                    3.4                   -5.1
22281                     3.4                    5.6                    1.0
22282                     3.0                    4.9                    0.7
22283                    -1.0                    0.8                   -1.9
22284                    -5.8                   -0.6                   -9.4

----- top10 ylimmät------------

       Vuosi  Kk  Pv  Ylin lämpötila (degC)  Alin lämpötila (degC)
18837   2010   7  29                   34.2                   18.6
12992   1994   7  28                   33.3                   13.8
21763   2018   8   2                   32.3                   17.7
22122   2019   7  27                   32.2                   13.7
18821   2010   7  13                   32.1                   18.1
18820   2010   7  12                   32.0                   15.4
21762   2018   8   1                   31.6                   12.8
21747   2018   7  17                   31.5                   13.8
10771   1988   6  28                   31.3                   16.0
12993   1994   7  29                   31.1                   16.4

----- yli 2.1.2020 -lämpötilat ------------

       Vuosi  Kk  Pv  Ylin lämpötila (degC)  Alin lämpötila (degC)
17541   2007   1  10                    6.5                   -0.3
5119    1973   1   6                    6.3                   -0.5
4393    1971   1  11                    5.9                    1.9

----- vrk:n lämpötilaero ------------

       Vuosi  Kk  Pv  Ylin lämpötila (degC)  Alin lämpötila (degC)  erotus
22269   2019  12  21                    0.4                    0.0     0.4
18944   2010  11  13                    0.7                    0.2     0.5
6559    1976  12  16                   -5.1                   -5.6     0.5
10628   1988   2   6                    0.4                   -0.1     0.5
7002    1978   3   4                    0.8                    0.3     0.5
4721    1971  12   5                    0.6                    0.1     0.5
22262   2019  12  14                    0.5                    0.0     0.5
22263   2019  12  15                    0.5                    0.0     0.5
5789    1974  11   7                    0.5                   -0.1     0.6
2882    1966  11  22                    0.3                   -0.3     0.6

## 5. Kunnat

Alla luetaan DataFrameen Excel-taulukko, jossa on tilastotietoja Suomen kunnnista (vuosilta 2017-2019)

Suodata/lajittele  pandasin avulla:
* tee uusi DataFrame jossa on kaikki kunnat jotka kuuluvat Pohjois-Savon, Etelä-Savon, Pohjois-Karjalan tai Etelä-Karjalan maakuntiin ja kuntamuoto on kaupunki.
* tulosta 10 kuntaa, joissa taajama-aste on yli 80% ja Keskustan kannatus 2019 eduskuntavaaleissa on suurin lajiteltuna Keskustan kannatuksen mukaan 
* datassa on kentät alle 15-vuotiaiden  ja yli 64-vuotiaiden osuudelle. Laske näiden avulla 15-64 vuotiaiden osuus ja tulosta kolme kuntaa, joissa tämä osuus on suurin.

In [2]:
import pandas as pd
df = pd.read_excel('https://student.labranet.jamk.fi/~varpe/datananal1k2020/kerta1/kunnat.xlsx')


print('\n----- maakuntien kaupungit ------------\n')
maakunnat = ['Pohjois-Savo', 'Etelä-Savo', 'Pohjois-Karjala', 'Etelä-Karjala']

df2 = df.loc[(df['maakunta'].isin(maakunnat)) & (df['kuntamuoto']=='Kaupunki')]

print(df2.head())

print('\n----- keskustan taajamakunnat ------------\n')

# selkeyden vuoksi tulostetaan tässä vain muutama kenttä
print(df[['kunta', 'Taajama-aste', 'ev19-KESK']][df['Taajama-aste']>80].sort_values('ev19-KESK', ascending=False).head(10))




# tässä oli monitulkintainen tehtävänanto, voi myös lukea että Keskustan kannatus on suurempi kuin muiden puolueiden kannatus...
print('\n----- keskustan taajamakunnat, tulkinta 2------------\n')

# selkeyden vuoksi tulostetaan tässä vain muutama kenttä
kentat = ['kunta', 'Taajama-aste', 'ev19-KESK']

#1. yritys
print(df[kentat][(df['Taajama-aste']>80) & (df['ev19-KESK']>df['ev19-SDP']) & (df['ev19-KESK']>df['ev19-PS']) & (df['ev19-KESK']>df['ev19-KOK']) & (df['ev19-KESK']>df['ev19-VIHR']) & (df['ev19-KESK']>df['ev19-RKP'])].sort_values('ev19-KESK', ascending=False).head(10))

#tästä puuttuu mm. Siilinjärvi, koska siellä RKP:n kannatus on NaN

# uusi yritys, korvataan puuttuvat kannatukset nollalla
kannatukset = ['ev19-KESK','ev19-PS', 'ev19-KOK', 'ev19-VIHR', 'ev19-RKP', 'ev19-SDP' ]
df[kannatukset] = df[kannatukset].fillna(0)
print(df[kentat][(df['Taajama-aste']>80) & (df['ev19-KESK']>df['ev19-SDP']) & (df['ev19-KESK']>df['ev19-PS']) & (df['ev19-KESK']>df['ev19-KOK']) & (df['ev19-KESK']>df['ev19-VIHR']) & (df['ev19-KESK']>df['ev19-RKP'])].sort_values('ev19-KESK', ascending=False).head(10))



print('\n----- 15-64 -vuotiaiden osuus ------------\n')

df['15-64%'] = 100-df['Alle 15-v. osuus%']-df['Yli 64-v. osuus%']

# selkeyden vuoksi tulostetaan tässä vain muutama kenttä
print(df[['kunta','15-64%']].sort_values('15-64%', ascending = False).head(3))

----- maakuntien kaupungit ------------

        kunta         maakunta                 seutukunta kaksikielisyys  \
44    Iisalmi     Pohjois-Savo       Ylä-Savon seutukunta            NaN
49     Imatra    Etelä-Karjala         Imatran seutukunta            NaN
55    Joensuu  Pohjois-Karjala        Joensuun seutukunta            NaN
96      Kitee  Pohjois-Karjala  Keski-Karjalan seutukunta            NaN
98  Kiuruvesi     Pohjois-Savo       Ylä-Savon seutukunta            NaN

   kuntamuoto  maapinta-ala  kokonaispinta-ala  Taajama-aste  Väkiluku  \
44   Kaupunki        763.03             872.20          76.3     21472
49   Kaupunki        155.01             191.28          97.6     26932
55   Kaupunki       2381.65            2750.97          89.4     76551
96   Kaupunki       1253.57            1724.38          56.2     10358
98   Kaupunki       1328.14            1422.90          50.8      8153

    Väkiluvun muutos%  ...  ev19-PS  ev19-KOK  ev19-KESK  ev19-VIHR  ev19-RKP  \
44               -0.8  ...     19.4      13.7       19.0        6.4       NaN
49               -1.2  ...     18.7      15.1        7.9        7.4       NaN
55                0.6  ...     17.0      12.0       17.2       15.0       NaN
96               -1.2  ...     21.7       5.5       39.2        3.8       NaN
98               -1.6  ...     21.9       7.7       33.9        2.6       NaN

    Alle 15-v. osuus%  Yli 64-v. osuus%  Ruotsinkielisten osuus%  \
44               15.5              25.4                      0.0
49               12.6              29.6                      0.1
55               13.8              21.4                      0.1
96               11.6              34.0                      0.0
98               14.5              29.4                      0.0

    Ulkomaan kansalaisten osuus%  Työttömyys%
44                           2.1         13.3
49                           3.9         16.8
55                           3.0         16.3
96                           3.0         17.5
98                           0.9         13.4

[5 rows x 21 columns]

----- keskustan taajamakunnat ------------

               kunta  Taajama-aste  ev19-KESK
305        Ylivieska          86.0       41.2
275           Tornio          87.8       37.9
217            Raahe          87.1       30.7
90           Kempele          96.2       30.5
88          Keminmaa          89.6       30.2
248      Siilinjärvi          82.4       26.2
243        Seinäjoki          91.1       24.4
166  Mänttä-Vilppula          83.1       23.0
101          Kokkola          88.2       22.7
229        Rovaniemi          90.2       22.7

----- keskustan taajamakunnat, tulkinta 2------------

         kunta  Taajama-aste  ev19-KESK
305  Ylivieska          86.0       41.2
275     Tornio          87.8       37.9
217      Raahe          87.1       30.7
90     Kempele          96.2       30.5
88    Keminmaa          89.6       30.2
243  Seinäjoki          91.1       24.4
69     Kajaani          88.1       22.7
101    Kokkola          88.2       22.7
229  Rovaniemi          90.2       22.7
180       Oulu          96.6       20.6
           kunta  Taajama-aste  ev19-KESK
305    Ylivieska          86.0       41.2
275       Tornio          87.8       37.9
217        Raahe          87.1       30.7
90       Kempele          96.2       30.5
88      Keminmaa          89.6       30.2
248  Siilinjärvi          82.4       26.2
243    Seinäjoki          91.1       24.4
69       Kajaani          88.1       22.7
101      Kokkola          88.2       22.7
229    Rovaniemi          90.2       22.7

----- 15-64 -vuotiaiden osuus ------------

        kunta  15-64%
33   Helsinki    68.7
268   Tampere    67.4
290    Vantaa    67.2